api_product_controllers:
    resource:
        path: ../src/Modules/Orders/Presentation/Controllers
        namespace: App\Modules\Orders\Presentation\Controllers
    type: attribute
    prefix: /api
    name_prefix: api_orders_